#!/bin/bash

####################################################################################################
# Author: Cuong. Duong Manh <cuongdm8499@gmailcom>
# Description: The collection of functions that are popular used in INI files.
####################################################################################################

# Set an option in an INI file iniset [-sudo] config-file section option value
# - if the file does not exist, it is created
function iniset {
  local xtrace
  xtrace=$(set +o | grep xtrace)
  set +o xtrace
  local sudo=""
  local sudo_option=""
  if [ $1 == "-sudo" ]; then
    sudo="sudo "
    sudo_option="-sudo "
    shift
  fi
  local file=$1
  local section=$2
  local option=$3
  local value=$4

  # Escape the ampersand character (&)
  value=$(echo $value | sed -e 's/&/\\&/g')

  if [[ -z $section || -z $option ]]; then
    $xtrace
    return
  fi

  if ! $sudo grep -q "^\[$section\]" "$file" 2>/dev/null; then
    # Add section at the end
    echo -e "\n[$section]" | $sudo tee --append "$file" >/dev/null
  fi
  if ! ini_has_option $sudo_option "$file" "$section" "$option"; then
    # Add it
    $sudo sed -i -e "/^\[$section\]/ a\\
$option = $value
" "$file"
  else
    local sep
    sep=$(echo -ne "\x01")
    # Replace it
    $sudo sed -i -e '/^\['${section}'\]/,/^\[.*\]/ s'${sep}'^\('"${option}"'[ \t]*=[ \t]*\).*$'${sep}'\1'"${value}"${sep} "$file"
  fi
  $xtrace
}

# Determinate is the given option present in the INI file ini_has_option [-sudo] config-file section
# option
function ini_has_option {
  local xtrace
  xtrace=$(set +o | grep xtrace)
  set +o xtrace
  local sudo=""
  if [ $1 == "-sudo" ]; then
    sudo="sudo "
    shift
  fi
  local file=$1
  local section=$2
  local option=$3
  local line

  line=$($sudo sed -ne "/^\[$section\]/,/^\[.*\]/ { /^$option[ \t]*=/ p; }" "$file")
  $xtrace
  [ -n "$line" ]
}
